# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcmoedavirtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedavirtual',
            name='cotacao',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
